// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: apipb/message.proto

package apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Detail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Detail) Reset() {
	*x = Detail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apipb_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_apipb_message_proto_rawDescGZIP(), []int{0}
}

func (x *Detail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_apipb_message_proto protoreflect.FileDescriptor

var file_apipb_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x70, 0x69, 0x70, 0x62, 0x22, 0x1c, 0x0a, 0x06,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x74, 0x72, 0x30, 0x37, 0x33, 0x31,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2d, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x2d, 0x62, 0x69, 0x6e, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x70,
	0x69, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apipb_message_proto_rawDescOnce sync.Once
	file_apipb_message_proto_rawDescData = file_apipb_message_proto_rawDesc
)

func file_apipb_message_proto_rawDescGZIP() []byte {
	file_apipb_message_proto_rawDescOnce.Do(func() {
		file_apipb_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_apipb_message_proto_rawDescData)
	})
	return file_apipb_message_proto_rawDescData
}

var file_apipb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apipb_message_proto_goTypes = []interface{}{
	(*Detail)(nil), // 0: apipb.Detail
}
var file_apipb_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apipb_message_proto_init() }
func file_apipb_message_proto_init() {
	if File_apipb_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apipb_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Detail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apipb_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apipb_message_proto_goTypes,
		DependencyIndexes: file_apipb_message_proto_depIdxs,
		MessageInfos:      file_apipb_message_proto_msgTypes,
	}.Build()
	File_apipb_message_proto = out.File
	file_apipb_message_proto_rawDesc = nil
	file_apipb_message_proto_goTypes = nil
	file_apipb_message_proto_depIdxs = nil
}
